language: java

script: ./mvnw verify

after_success:
  - ./mvnw clean verify jacoco:report coveralls:report

jdk:
  - openjdk8

branches:
  only:
    - master


deploy:
  provider: script
  script: ./mvnw compile jib:build -Djib.to.auth.username=$REGISTRY_USERNAME -Djib.to.auth.password=$REGISTRY_PASSWORD
  on:
    condition: tag IS present

cache:
  directories:
    - $HOME/.m2

env:
  global:
    - secure: "dHAWwjzSbw8wt9aZf2cs+mvWrYNLiyzXkCckYY2vGLUd1EtfJG4jB899FLiQeShvS+v+64xm8AEihZzAPq2Y2C3D0cpzKRQhvu1cfuGszyFxetyl9K0pl2t1EPSbOgo0T2c5ruk2XqPgRoKIxpHMSQRLPuk0DlFRR3SOeJP4obAH7PuDnOGkjmz9Bn7Fk9ZOGDZ2BDna2A+9L4mecQKYrOC4AGZm5dmF6Vr7Gt3GeGPKv6f3RhQAyKyRg+52wmerCWdyRQSnzR06F9M5Jd93FoZPL/IjcHQIMVseBDGrc4KTUaUmj3SxGHZwQ7V1BqtM6ENwhq7tFQvujX5x45pbxpspaIlQwfVuzwumukGVHjyBN0BtPhWf9yvmgpJntNNuZ96hlEuOSzl8+75jOV13ZRyU91r8SiiO8qKlK9odp2yAsMsepzjJsaCdY6Ki301xn97KTl4drdNIHo6BzBvMTKFeXjoXTO8ohpxJf/IKKwXqDfW2g2Z5N/vi5kIHbVf+2+fRruRABo6RIrWlyy4PS8NvgddYH7aIPnEWSeqAePZmTu+WxoNFZ/tD4arMu/zDSTac3SFYsbjfOHAHpjmlUTnNKeefPCoO68TBxsluE9Yn4wVbHAg4fdgxlTPh0bhIdKH+Ehc5KnHDGBTeSjHXj2TrIVgHvMp1iypepXYWOY0=" # REGISTRY_USERNAME
    - secure: "qQE4PA80pwZqJ8hVx0J69ZpxCZXkQ0+PTBuwQdbuNuwY2EixZ28K1SEDvPOyULMkRgqW9ZkqrF5W9w6vvwexJZ6jgU1Y8rm89Dzxmyyq3uT92PSeKtvKsVknoMfMayavR2EpVLV7B+oTa0Zvo8Lz1hL4LxmYRGnvNp3Vs2cg9vnCTZNmzWuEVv8h0Ta+fcUusJpok1dlPCaOFw7SBfhgrUe+BxPrIFXQ9hu54/oy7j3EHhAWUMb/YAPmGc8hPlcKKwILDaFxajFpoSdPEIr7LND0etQz21ZOs59PAn1AYMA0xdu9RwlbtvNdXJZdEp4xjmqoyGrGf9652kCy5bjKT0f1Js0p6tYKhePicH8GY2Er4Bw1ygQyVHVENde9fM9nPeOHc3T0lHJzWeWIlE0vtvUP2TTRbUKYflXejIOIShx6CbU0uZGDF6NLKRzgiFgJ0XMWsHvmSKbDw3v9yrr5DqFlEQhAxvnqtWjJpE8LBgb7ZsPr5OlGt8giJm2erYjZGTGnd/yzOIrm+EntJbdBIxMNaB2hB/NbKc5mDqDkdiXnFjp9ZG7wITdIHbaEdHXNUFs4qWjg1kFXq8G99/laVpNTsFfKpNvgqR6JDCpWAwTQ9trWdmEACVzIr93mVDRldcyMq9IIGnX4+OAmpLMD1zu3qSbyM98X+YSUBXdRU7k=" # REGISTRY_PASSWORD
