name: Release

on:
  push:
    tags:
      - 'urlaubsverwaltung*'

jobs:
  release:
    runs-on: ubuntu-22.04
    env:
      MAVEN_CLI_OPTS: "--batch-mode --errors --fail-at-end --show-version"
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: 11
          cache: 'maven'
      - name: Cache npm dependencies
        uses: actions/cache@v3
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-
      - name: Build jar with Maven
        run: >
          ./mvnw $MAVEN_CLI_OPTS
          -Pcoverage
          clean verify
      - name: Build war with Maven
        run: >
          ./mvnw $MAVEN_CLI_OPTS
          -DskipTests -Dpackaging.layout=war
          package
      - name: Extract release tag
        id: vars
        run: echo "version=${GITHUB_REF#refs/*/urlaubsverwaltung-}" >> $GITHUB_OUTPUT
      - name: Create Release
        uses: softprops/action-gh-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          name: Release Urlaubsverwaltung ${{ steps.vars.outputs.version }}
          body_path: .chglog/${{ steps.vars.outputs.version }}.md
          files: |
            ./target/urlaubsverwaltung-*.war
            ./target/urlaubsverwaltung-*.jar
      - name: Publish docker image to Docker Hub
        run: >
          ./mvnw $MAVEN_CLI_OPTS
          docker:build
          docker:push
          -Ddocker.name=synyx/urlaubsverwaltung
          -Ddocker.push.registry=registry.hub.docker.com
          -Ddocker.push.username=${{ secrets.DOCKER_USERNAME }}
          -Ddocker.push.password=${{ secrets.DOCKER_PASSWORD }}
      - name: Publish docker image to Docker Hub urlaubsverwaltung
        run: >
          ./mvnw $MAVEN_CLI_OPTS
          docker:build
          docker:push
          -Ddocker.name=urlaubsverwaltung/urlaubsverwaltung
          -Ddocker.push.registry=registry.hub.docker.com
          -Ddocker.push.username=${{ secrets.DOCKER_UV_USERNAME }}
          -Ddocker.push.password=${{ secrets.DOCKER_UV_TOKEN }}
      - name: Publish docker image to GitHub Container Registry
        run: >
          ./mvnw $MAVEN_CLI_OPTS
          docker:build
          docker:push
          -Ddocker.name=urlaubsverwaltung/urlaubsverwaltung
          -Ddocker.push.registry=ghcr.io
          -Ddocker.push.username=${{ github.actor }}
          -Ddocker.push.password=${{ secrets.CR_PAT }}
          -Ddocker.pull.username=${{ secrets.DOCKER_USERNAME }}
          -Ddocker.pull.password=${{ secrets.DOCKER_PASSWORD }}
