name: Release Trigger

on:
  workflow_dispatch:
    inputs:
      milestoneId:
        description: 'Milestone ID'
        required: true
        default: '1'
      releaseVersion:
        description: 'Release version'
        required: true
        default: 'x.xx.x'
      nextVersion:
        description: 'Next version'
        required: true
        default: 'x.xx.x-SNAPSHOT'

jobs:
  trigger-release:
    runs-on: ubuntu-22.04
    env:
      MAVEN_CLI_OPTS: "--batch-mode --errors --fail-at-end --show-version"
    steps:
      - uses: actions/checkout@v4
        with:
          persist-credentials: false
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: 11
          cache: 'maven'
      - name: Cache npm dependencies
        uses: actions/cache@v3
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-
      - name: Build
        run: >
          ./mvnw $MAVEN_CLI_OPTS
          -Pcoverage
          clean verify
      - name: Create Release Notes
        uses: docker://decathlon/release-notes-generator-action:3.1.5
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          OUTPUT_FOLDER: .chglog/
          FILENAME: ${{ github.event.inputs.releaseVersion }}
      - name: Setup git user
        uses: fregante/setup-git-user@v2
      - name: Commit Release Notes
        run: |
          git add .chglog/*.md
          git commit -m "[skip ci] Add release notes for version ${{ github.event.inputs.releaseVersion }}"
      - name: Push Release Notes
        uses: ad-m/github-push-action@v0.6.0
        with:
          github_token: ${{ secrets.AM_PAT }}
          branch: ${{ github.ref }}
      - name: Set release version
        run: ./mvnw $MAVEN_CLI_OPTS versions:set -DnewVersion=${{ github.event.inputs.releaseVersion }}
      - name: Commit release version
        run: git add pom.xml && git commit -m "New Release Version urlaubsverwaltung-${{ github.event.inputs.releaseVersion }}"
      - name: Add release tag
        run: git tag -a -m "urlaubsverwaltung-${{ github.event.inputs.releaseVersion }}" urlaubsverwaltung-${{ github.event.inputs.releaseVersion }}
      - name: Push release version
        uses: ad-m/github-push-action@v0.6.0
        with:
          github_token: ${{ secrets.AM_PAT }}
          branch: ${{ github.ref }}
      - name: Set new snapshot version
        run: ./mvnw $MAVEN_CLI_OPTS versions:set -DnewVersion=${{ github.event.inputs.nextVersion }}
      - name: Commit new snapshot version
        run: git add pom.xml && git commit -m "Prepare Next Snapshot Version urlaubsverwaltung-${{ github.event.inputs.nextVersion }}"
      - name: Push snapshot commit
        uses: ad-m/github-push-action@v0.6.0
        with:
          github_token: ${{ secrets.AM_PAT }}
          branch: ${{ github.ref }}
